name: Automated JMeter Tests
 
on:
  workflow_dispatch:  # Allow manual trigger
    inputs:
      users:
        description: 'Number of users (threads)'  # This will be the label
        required: true
        type: choice  # Dropdown selection
        options: 
          - 1
          - 5
          - 10
          - 20
          - 50
        default: 1  # Default option
      ramp_up:  # Input for ramp-up time
        description: "Ramp-up time in seconds"
        required: true
        default: 100
jobs:
  automated-jmeter-tests:
    runs-on: windows-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Set Up JMeter
        run: choco install jmeter -y  # Use Chocolatey to install JMeter on Windows
 
      - name: Check JMeter Version
        run: jmeter -v  # Verify JMeter installation and version
 
      - name: Run JMeter Tests
        run: jmeter -n -t Demoblaze.jmx -Jusers=1 -Jramp_up=1 -l results/result.jtl -e -o html -j results/jmeter.log
 
      - name: List Results Directory
        run: |
          echo "Listing results directory:"
          dir results  # Use 'dir' to list the contents of results folder in Windows
 
      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results/result.jtl
 
      - name: Upload JMeter Log
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-log
          path: results/jmeter.log
 
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: html  # Uploads the entire HTML report folder
          if-no-files-found: error
 
